config/routes.rb
EchoNest::Application.routes.draw do
  root  'pages#home'
  match '/help',     to: 'pages#help',     via: 'get'
  match '/about_us', to: 'pages#about_us', via: 'get'
  match '/contact',  to: 'pages#contact',  via: 'get'
  match '/search',   to: 'search#search',  via: 'post'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def help
  end

  def about_us
  end

  def contact
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  attr_accessor :submit_fetch, :result_fetch

  def search
    if params[:artist]
      logger.info "******************************************************************"
      logger.info "\tHERE IS THE TERM SEARCHED FOR: #{params[:artist]}"
      logger.info "******************************************************************"
      logger.info "\tHERE IS WHAT WAS SEARCHED FOR: #{params[:en_search_field]}"
      logger.info "******************************************************************"
      begin
        gon.submit_fetch = ENAPIFetch.artist_search(params[:en_search_field])["response"]["biographies"]
        logger.info "#{submit_fetch}"
        logger.info "#{gon.submit_fetch}"
      rescue ENSearchUrlError => e
        redirect_to :root, :flash => { :error => 'Invalid URL' }
      end
    elsif params[:song]
      logger.info "******************************************************************"
      logger.info "\tHERE IS THE TERM SEARCHED FOR: #{params[:song]}"
      logger.info "******************************************************************"
      logger.info "\tHERE IS WHAT WAS SEARCHED FOR: #{params[:en_search_field]}"
      logger.info "******************************************************************"
      begin
        gon.submit_fetch = ENAPIFetch.song_search(params[:en_search_field])["response"]["songs"]
      rescue ENSearchUrlError => e
        redirect_to :root, :flash => { :error => 'Invalid URL' }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%footer.footer.fluid
  %small
    = link_to 'Echo Nest', 'http://www.echonest.com'

  %nav
    %ul
      %li
        = link_to 'About Us',   about_us_path
      %li
        = link_to 'Contact', contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.fluid

  .navbar-inner

    .date.center
      <script type="text/javascript">
      <!--
      // Array of day names
      var dayNames = new Array("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday");
      var now = new Date();
      document.write("Happy " + dayNames[now.getDay()] + ".");
      // -->
      </script>

    .container

      = link_to 'Echo Nest Search', root_path, id: 'logo'

      %nav

        %ul.nav.pull-right
          %li
            = link_to 'Home', root_path
          %li
            = link_to 'Help', help_path
          %li
            = link_to 'About Us', about_us_path

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.haml
!!! html

%html{ "ng-app" => "ENSearch" }

  %head
    = include_gon
    %title EchoNest
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = render 'layouts/shim'

    %body{ "ng-controller" => "ENSearchCtrl" }

      = render 'layouts/header'

      .container.fluid

        = yield
        = render 'layouts/footer'

app/views/pages/about_us.html.haml
.center.hero-unit.fluid

  %h1 Pages#about_us
  %p Find me in app/views/pages/about_us.html.erb

app/views/pages/contact.html.haml
.center.hero-unit.fluid

  %h1 Pages#contact
  %p Find me in app/views/pages/contact.html.erb

app/views/pages/help.html.haml
.center.hero-unit.fluid

  %h1 Pages#help
  %p Find me in app/views/pages/help.html.erb

app/views/pages/home.html.haml
.center.hero-unit.fluid

  %h1  EchoNest Search

  %h2  A search engine for your music.

  .row-fluid.search-query
    = form_tag(search_path) do
      = search_field "", "en_search_field", :class => "search-query", :placeholder => "Enter Artist or Song"
      = submit_tag "Submit", :class => "btn btn-primary", :id => "btnSearch", "disabled" => true
      %p.options
        = radio_button_tag "artist", "search_by_artist", :id => "btnArtist"
        Artist
        = radio_button_tag "song", "search_by_song", :id => "btnSong"
        Song

app/views/search/search.html.haml
.center.hero-unit.fluid

  %h1 Search Results

  %p Here's what we found.

  %ul.search_list
    %li{ "ng-repeat" => "search in searches" }
      %a{"href" => "#" + "{{$index}}"} {{search.site}} {{search.title}} by {{search.artist_name}}

  %p
  %br

  %ul.search
    %li{ "ng-repeat" => "search in searches" }
      %a{"href" => "{{search.url}}", "target" => "_blank", "id" => "{{$index}}"} {{search.url}}
      %p From: {{search.site}}
      %p {{search.text}}